# Aicademy 360

# Bank Customer Churn Prediction using ANN

### Steps

- * Import Libraries
- 1. Raw Customer Data
- 2. Preprocessing
- 3. Feature Engineering
- 4. Scaling
- 5. Train Test Split
- 6. Build ANN Model
- 7. Trai the ANN model
- 8. Save the model
- 9. Deploy it on streamlit


- Customer Stayed = 0
- Customer Left = 1

In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder


import pickle

In [2]:
# load the customer churn dataset.

data = pd.read_csv('Churn_Modelling.csv')

In [3]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
data.shape

(10000, 14)

In [5]:
data.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='str')

In [6]:
## Preprocessing the data

data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)   

data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [7]:
# Feature Engineering

label_encoder_gender = LabelEncoder()

In [8]:
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])


data.head(10)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
5,645,Spain,1,44,8,113755.78,2,1,0,149756.71,1
6,822,France,1,50,7,0.00,2,1,1,10062.80,0
7,376,Germany,0,29,4,115046.74,4,1,0,119346.88,1
8,501,France,1,44,4,142051.07,2,0,1,74940.50,0
9,684,France,1,27,2,134603.88,1,1,1,71725.73,0

In [9]:
onehot_encoder_geo = OneHotEncoder()


geo_encoder = onehot_encoder_geo.fit_transform(
    data[["Geography"]]
).toarray()

geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [10]:
onehot_encoder_geo.get_feature_names_out(
    ["Geography"]
)

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [11]:
geo_encoded_df = pd.DataFrame(
    geo_encoder,
    columns=onehot_encoder_geo.get_feature_names_out(
        ["Geography"]
    )
)

geo_encoded_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [12]:
data = pd.concat(
    [
        data.drop("Geography", axis=1),
        geo_encoded_df
    ],
    axis=1
)

data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [13]:
with open("label_encoder_gender.pkl", "wb") as file:
    pickle.dump(
        label_encoder_gender,
        file
    )

with open("onehot_encoder_geo.pkl", "wb") as file:
    pickle.dump(
        onehot_encoder_geo,
        file
    )

print("Encoders saved successfully.")

Encoders saved successfully.

In [14]:

X = data.drop(
    "Exited",
    axis=1
)

y = data["Exited"]

print("Input feature shape:", X.shape)
print("Target shape:", y.shape)

print("\nInput columns:")
print(list(X.columns))

Input feature shape: (10000, 12)
Target shape: (10000,)

Input columns:
['CreditScore', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Geography_France', 'Geography_Germany', 'Geography_Spain']

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (8000, 12)
X_test : (2000, 12)
y_train: (8000,)
y_test : (2000,)

In [16]:
scaler = StandardScaler()


X_train = scaler.fit_transform(X_train)


X_test = scaler.transform(X_test)

print("Scaled X_train shape:", X_train.shape)
print("Scaled X_test shape :", X_test.shape)

Scaled X_train shape: (8000, 12)
Scaled X_test shape : (2000, 12)

In [17]:
with open("Scaler.pkl", "wb") as file:
    pickle.dump(
        scaler,
        file
    )

print("Scaler saved successfully.")

Scaler saved successfully.

In [18]:

import tensorflow as tf

from tensorflow.keras.models import Sequential

from tensorflow.keras.layers import Dense

from tensorflow.keras.callbacks import (
    EarlyStopping,
    TensorBoard,
)

import datetime

print("TensorFlow version:", tf.__version__)

2026-10-17 18:15:25.575266: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

TensorFlow version: 2.16.2

In [19]:
input_shape = (
    X_train.shape[1],
)

print("ANN input shape:", input_shape)

ANN input shape: (12,)

In [20]:
model = Sequential([
    Dense(
        64,
        activation="relu",
        input_shape=(X_train.shape[1],)
    ),

    Dense(
        32,
        activation="relu"
    ),

    Dense(
        1,
        activation="sigmoid"
    )
])

/Users/malik96/Developer/1.Aicademy360 AI_Eng_B1/3 - Deep Learning  & Generative AI/Class 16-17-18/churn1/lib/python3.11/site-packages/keras/src/layers/core/dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [21]:
first_layer_parameters = (12 * 64) + 64

print("First hidden layer parameters:",first_layer_parameters)

First hidden layer parameters: 832

In [22]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

## Model Training

In [23]:
optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)

In [24]:
loss_function = tf.keras.losses.BinaryCrossentropy()

loss_function

In [25]:
model.compile(
    optimizer=optimizer,
    loss=loss_function,
    metrics=["accuracy"]
)

In [26]:
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

tensorboard_callback = TensorBoard(
    log_dir=log_dir,
    histogram_freq=1
)

print("Tensorboard log directory:", log_dir)

Tensorboard log directory: logs/fit/20261017-183552

In [27]:
early_stopping_callback = EarlyStopping(
    monitor="val_loss",
    patience=10,
    restore_best_weights=True
)

In [28]:
## Train the model

history = model.fit(
    X_train,
    y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[tensorboard_callback, early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.8319 - loss: 0.4016 - val_accuracy: 0.8550 - val_loss: 0.3583
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8529 - loss: 0.3557 - val_accuracy: 0.8585 - val_loss: 0.3478
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8590 - loss: 0.3470 - val_accuracy: 0.8605 - val_loss: 0.3550
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8597 - loss: 0.3432 - val_accuracy: 0.8650 - val_loss: 0.3421
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8594 - loss: 0.3400 - val_accuracy: 0.8610 - val_loss: 0.3460
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8611 - loss: 0.3380 - val_accuracy: 0.8530 - val_loss: 0.3589
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8625 - loss: 0.3353 - val_accuracy: 0.8595 - val_loss: 0.3540
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8634 - loss: 0.3342 - val_accuracy: 0.8605 - val_loss: 0.3522
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8630 - loss: 0.3308 - val_accuracy: 0.8570 - val_loss: 0.3509
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8652 - loss: 0.3272 - val_accuracy: 0.8560 - val_loss: 0.3623
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8661 - loss: 0.3274 - val_accuracy: 0.8555 - val_loss: 0.3470
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8665 - loss: 0.3227 - val_accuracy: 0.8605 - val_loss: 0.3573
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8681 - loss: 0.3242 - val_accuracy: 0.8560 - val_loss: 0.3500
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8701 - loss: 0.3173 - val_accuracy: 0.8590 - val_loss: 0.3591

In [29]:
test_loss, test_accuracy = model.evaluate(X_test, y_test, verbose=0)

print(f"Test Loss: {test_loss:.4f}")

print(f"Test Accuracy: {test_accuracy:.4f}")

Test Loss: 0.3421
Test Accuracy: 0.8650

In [30]:
model.save("model.h5")

print("Saved model .h5 file successfully.")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Saved model .h5 file successfully.